# The settings are inherited from common repository repo-settings (same file name and location)
# You can append settings that are deeply-merged with the inherited settings.
#
# When you have installed the GitHub App "repo-settings" in this repository,
# any change of this settings.yml file is detected by the GitHub App and
# the settings of this repository are updated immediately.

_extends: repo-settings:.github/common-settings-v2.yml

# repo-specific settings
#
repository:
  # By changing this field, you rename the repository.
  name: "terraform-ibm-landing-zone-vsi"

  # The description is displayed under the repository name on the
  # organization page and in the 'About' section of the repository.
  description: "Creates virtual server instances (VSI) across multiple subnets with any number of block storage volumes that are connected by any number of load balancers"
  topics: core-team, terraform, ibm-cloud, terraform-module, slz, slz-vsi, landing-zone
