---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-vsi-vpc
    kind: solution
    catalog_id: f64499c8-eb50-4985-bf91-29f9e605a433
    offering_id: 28e2b12c-858f-4ae8-8717-60db8cec2e6e
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
          scope_resource_group_var_name: existing_resource_group_name
        pre_validation: "tests/scripts/pre-validation-deploy-vpc.sh"
        post_validation: "tests/scripts/post-validation-destroy-vpc.sh"
